KinsonDigital/CICD

.github/workflows/build-status-check.yml, .github/workflows/unit-testing-status-check.yml
<h1 style="font-weight:bold" align="center">Preview Release Pull Request</h1>
``` xml
```
</details>
``` xml
Syntax: release/v<major>.<minor>.<patch>
Example: release/v1.2.3
```
</details>
``` xml
Syntax: release/v<major>.<minor>.<patch>
Example: release/v1.2.3
```
</details>
- One issue per pull request.
=> 🚀Preview Release

.github/workflows/build-status-check.yml, .github/workflows/unit-testing-status-check.yml, CICD/CICD.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix project dotnet tool setup

CICD/WorkflowTemplates/build-status-check.yml, CICD/WorkflowTemplates/feature-pr-status-check.yml, CICD/WorkflowTemplates/hotfix-pr-status-check.yml, CICD/WorkflowTemplates/prev-feature-pr-status-check.yml, CICD/WorkflowTemplates/prev-release-pr-status-check.yml, CICD/WorkflowTemplates/prev-release.yml, CICD/WorkflowTemplates/prod-release-pr-status-check.yml, CICD/WorkflowTemplates/prod-release.yml, CICD/WorkflowTemplates/unit-test-status-check.yml
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Adjust workflow templates to restore dotnet tools

.nuke/build.schema.json, .nuke/parameters.json, CICD/CICD.Common.Build.cs, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/CICD.Requirements.cs, CICD/CICD.StatusChecks.cs, CICD/CICD.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Change owner and repos name setup

.nuke/build.schema.json, .nuke/parameters.json, CICD/CICD.Common.Build.cs, CICD/CICD.Common.Tests.cs, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/CICD.Requirements.cs, CICD/CICD.StatusChecks.cs, CICD/CICD.cs, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Change how release note paths work

README.md
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Update README

CICD/CICD.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Add license in nuget package

CICD/App.cs, CICD/Configuration.cs, CICD/Enums.cs, CICD/ExtensionMethods.cs, CICD/Factories/IHttpClientFactory.cs, CICD/Factories/ServiceFactory.cs, CICD/Guards/EnsureThat.cs, CICD/Services/CurrentDirService.cs, CICD/Services/ExecutionContextService.cs, CICD/Services/GitHubActionsService.cs, CICD/Services/GitHubClientService.cs, CICD/Services/GitHubTokenService.cs, CICD/Services/GitRepoService.cs, CICD/Services/ICurrentDirService.cs, CICD/Services/IExecutionContextService.cs, CICD/Services/IGitHubActionsService.cs, CICD/Services/IGitHubClientService.cs, CICD/Services/IGitHubTokenService.cs, CICD/Services/IGitRepoService.cs, CICD/Services/IJsonService.cs, CICD/Services/ISecretService.cs, CICD/Services/IWorkflowService.cs, CICD/Services/JsonService.cs, CICD/Services/SecretService.cs, CICD/Services/WorkflowService.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Refactor classes to internal and/or sealed

CICD/CICD.Common.Build.cs, CICD/CICD.Common.Tests.cs, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/CICD.Requirements.cs, CICD/CICD.StatusChecks.cs, CICD/CICD.cs, CICD/Configuration.cs, CICD/ExtensionMethods.cs, CICD/Services/GitHubActionsService.cs, CICD/Services/NugetDataService.cs, CICD/Services/SecretService.cs, CICD/Services/WorkflowService.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Handle GitHubActionsService issue

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Pull request is 0 error

CICD/Enums.cs, CICD/ExtensionMethods.cs, CICD/Factories/ServiceFactory.cs, CICD/Guards/EnsureThat.cs, CICD/Services/GitHubActionsService.cs, CICD/Services/IExecutionContextService.cs, CICD/Services/IGitHubActionsService.cs, CICD/Services/IGitHubTokenService.cs, CICD/Services/IWorkflowService.cs, CICD/Services/NugetDataService.cs, Documentation/Branching.md, Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.4.md, Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.5.md, Documentation/ReleaseNotes/PreviewReleases/Release-Notes-v1.0.0-preview.6.md, Testing/CICDTests/Helpers/AssertExtensions.cs, Testing/CICDTests/Services/GitHubActionsServiceTests.cs, Testing/CICDTests/Services/GitHubClientServiceTests.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Review and fix documentation 

.nuke/parameters.json, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/CICD.Requirements.cs, CICD/CICD.StatusChecks.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Issue with detecting open milestone pull requests

CICD.sln.DotSettings, CICD/CICD.Common.cs, CICD/CICD.Requirements.cs, CICD/Enums.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Non existing nuget not handled correctly

.nuke/build.schema.json, CICD/App.cs, CICD/CICD.Common.Build.cs, CICD/CICD.Common.Tests.cs, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/CICD.Requirements.cs, CICD/CICD.cs, CICD/CICD.csproj, CICD/ExtensionMethods.cs, CICD/Factories/HttpClientFactory.cs, CICD/ISolutionWrapper.cs, CICD/Reactables/ProductNameReactable.cs, CICD/Reactables/SolutionReactable.cs, CICD/Services/BranchValidatorService.cs, CICD/Services/ISolutionService.cs, CICD/Services/ISolutionWrapper.cs, CICD/Services/PullRequestService.cs, CICD/Services/SolutionService.cs, CICD/Services/SolutionWrapper.cs, CICD/SolutionWrapper.cs, Testing/CICDTests/Helpers/AssertExtensions.cs, Testing/CICDTests/Reactables/SolutionReactableTests.cs, Testing/CICDTests/Services/SolutionServiceTests.cs, Testing/CICDTests/SolutionWrapperTests.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Create new solution service

.nuke/build.schema.json, CICD/CICD.Common.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Add target to show current version

CICD/ExtensionMethods.cs, Testing/CICDTests/ExtensionMethodsTests.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Create unit tests for extension methods

CICD/CICD.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Exception thrown for preview releases

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix simple logging issue

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Adjust logging of requirement method

CICD.sln.DotSettings, CICD/CICD.Common.cs, CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix issue with creating milestone description

CICD/CICD.Common.cs, CICD/CICD.Requirements.cs, CICD/CICD.StatusChecks.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix requirement issue with hotfix pr status checks

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix release note title logging issue

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Simple logging adjustment

CICD/CICD.Common.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Change milestone description

CICD/CICD.Requirements.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix logging issue with milestone assignment check

CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Release PR status checks not working correctly

CICD.sln.DotSettings, CICD/CICD.Requirements.cs, CICD/ExtensionMethods.cs, Testing/CICDTests/ExtensionMethodsTests.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Ignore QA issues in release notes

CICD/CICD.Common.cs, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Handle tag protection rules

.nuke/build.schema.json, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Improve logging with incorrect PR number

CICD/CICD.Release.Preview.cs, CICD/CICD.Release.Production.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix issue with preview releases

CICD/CICD.Requirements.cs, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Change how assigned issues are checked

CICD/CICD.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Fix bug with twitter announcements

.github/workflows/build-status-check.yml, .github/workflows/preview-release.yml, .github/workflows/unit-testing-status-check.yml, CICD.sln.DotSettings, CICD/CICD.csproj, Testing/CICDTests/CICDTests.csproj, Testing/DotNetToolTesting/DotNetToolTesting.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Update project to latest dotnet and language version

.github/workflows/preview-release.yml, CICD/WorkflowTemplates/build-pr-status-check.yml, CICD/WorkflowTemplates/feature-pr-status-check.yml, CICD/WorkflowTemplates/hotfix-pr-status-check.yml, CICD/WorkflowTemplates/prev-feature-pr-status-check.yml, CICD/WorkflowTemplates/prev-release-pr-status-check.yml, CICD/WorkflowTemplates/prev-release.yml, CICD/WorkflowTemplates/prod-release-pr-status-check.yml, CICD/WorkflowTemplates/prod-release.yml, CICD/WorkflowTemplates/unit-test-pr-status-check.yml
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Update workflow generation 

.nuke/build.schema.json, .nuke/parameters.json, .run/PrevRelease - PreviewReleasePRStatusCheck.run.xml, CICD/CICD.Requirements.cs, CICD/CICD.cs, CICD/CICD.csproj, CICD/ExtensionMethods.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Add ability to skip nuget checks

CICD/Services/ReadMeService.cs
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🐛Cannot use CICD

CICD.sln, README.md, codecov.yml
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Setup codecov 

.github/workflows/preview-release.yml
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Update action in preview release workflow

CICD/CICD.csproj, Testing/CICDIntegrationTests/CICDIntegrationTests.csproj, Testing/CICDTests/CICDTests.csproj
``` xml
```
</details>
``` xml
```
</details>
``` xml
``` …
=> 🚧Update NUKE nuget package
